document.documentElement.classList.add('js');

const LANGUAGE_KEY = 'fluffy-cakes-language';
const copy = {
  common: {
    skip: ['Skip to content', 'Saltar para o conteúdo'],
    home: ['Home', 'Início'], menu: ['Menu', 'Menu'], story: ['Our story', 'A nossa história'], gallery: ['Gallery', 'Galeria'],
    enquire: ['Enquire', 'Fazer um pedido'], email: ['Email', 'Email'], whatsapp: ['WhatsApp', 'WhatsApp'],
    openNav: ['Open navigation', 'Abrir navegação'], closeNav: ['Close navigation', 'Fechar navegação'],
    languageLabel: ['Language', 'Idioma'], english: ['English', 'Inglês'], portuguese: ['Português', 'Português'],
    footer: ['© 2026 Fluffy Cakes · Karen Guilaze', '© 2026 Fluffy Cakes · Karen Guilaze'],
    homeLabel: ['Fluffy Cakes home', 'Página inicial da Fluffy Cakes'], logoAlt: ['FC by Karen Guilaze', 'FC por Karen Guilaze'],
    whatsappLink: ['WhatsApp +351 929 106 710 ↗', 'WhatsApp +351 929 106 710 ↗']
  },
  home: {
    title: ['Fluffy Cakes — Karen Guilaze', 'Fluffy Cakes — Karen Guilaze'], description: ['Fluffy Cakes by Karen Guilaze — elegant cakes and sweet moments, made with care.', 'Fluffy Cakes por Karen Guilaze — bolos elegantes e momentos doces, feitos com cuidado.'],
    eyebrow: ['Small moments, beautifully made', 'Pequenos momentos, feitos com beleza'], hero: ['Simply<br><em>Fluffy.</em>', 'Simplesmente<br><em>Fluffy.</em>'], lead: ['Thoughtful cakes and sweet details for the moments you want to remember.', 'Bolos pensados ao pormenor e detalhes doces para os momentos que quer recordar.'], explore: ['Explore the selection', 'Conheça a seleção'], conversation: ['Start a conversation', 'Inicie uma conversa'], signature: ['Made with patience, care and a little bit of joy.', 'Feito com paciência, cuidado e um pouco de alegria.'], art: ['A little sweetness<span>for every kind of occasion</span>', 'Um pouco de doçura<span>para qualquer ocasião</span>'], artAlt: ['Karen Guilaze presenting a white teddy-bear cake', 'Karen Guilaze apresenta um bolo branco com um ursinho'], feeling: ['The feeling', 'A sensação'], more: ['More than<br>a cake.', 'Mais do que<br>um bolo.'], demoIntro: ['Fluffy Cakes is a demo concept for a warm, elegant bakery brand built around simple design, beautiful details and the pleasure of sharing something made especially for you.', 'Fluffy Cakes é um conceito de demonstração de uma marca de pastelaria acolhedora e elegante, baseada num design simples, detalhes bonitos e no prazer de partilhar algo feito especialmente para si.'],
    story: ['There is something special about a dessert made with intention. It slows the room down, gives people a reason to gather and turns an ordinary moment into a memory.', 'Há algo de especial numa sobremesa feita com intenção. Abranda o ritmo, dá às pessoas uma razão para se reunirem e transforma um momento comum numa memória.'], side: ['Every detail has a purpose: soft textures, considered flavours and a finish that feels effortless. This is sweetness with a point of view.', 'Cada detalhe tem um propósito: texturas suaves, sabores pensados e um acabamento que parece natural. Esta é uma doçura com uma identidade própria.'], lines: [['Made for the moment','Feito para o momento'], ['Finished by hand','Finalizado à mão'], ['Shared with joy','Partilhado com alegria']], taste: ['A first taste','Uma primeira prova'], selection: ['The selection.','A seleção.'], menuIntro: ['A starting point for the Fluffy Cakes collection. The final menu, flavours and ordering details can be added as the brand grows.', 'Um ponto de partida para a coleção Fluffy Cakes. O menu final, os sabores e os detalhes das encomendas poderão ser acrescentados à medida que a marca cresce.'], cards: [['Signature cakes','Bolos de assinatura','Soft layers, delicate finishes and a centrepiece made for the table.','Camadas macias, acabamentos delicados e um centro de mesa feito para partilhar.','Celebration · Custom','Celebração · Personalizado'], ['Little treats','Pequenas tentações','Beautiful individual pieces for gifting, sharing or keeping all to yourself.','Peças individuais bonitas para oferecer, partilhar ou guardar só para si.','Boxes · Sweet details','Caixas · Detalhes doces'], ['Made for you','Feito para si','A personal design for birthdays, milestones and the moments in between.','Um design pessoal para aniversários, marcos importantes e os momentos entre eles.','Bespoke · Memorable','Personalizado · Memorável']], quote: ['“The best things in life are made to be shared.”','“As melhores coisas da vida são feitas para partilhar.”'], contactKicker: ['Let’s make something lovely','Vamos criar algo bonito'], sweet: ['Have a sweet idea?','Tem uma ideia doce?'], contactIntro: ['Tell us what you are celebrating, and we’ll start shaping something beautiful around it.','Conte-nos o que está a celebrar e começaremos a dar forma a algo bonito à sua volta.']
  },
  menu: { title:['Menu — Fluffy Cakes','Menu — Fluffy Cakes'], description:['Fluffy Cakes menu demo','Demonstração do menu Fluffy Cakes'], eyebrow:['A first taste','Uma primeira prova'], hero:['Made to be<br><em>remembered.</em>','Feito para ser<br><em>recordado.</em>'], lead:['A demo menu for the Fluffy Cakes collection. The final flavours, sizes and prices can be shaped around the brand’s real offer.','Um menu de demonstração para a coleção Fluffy Cakes. Os sabores, tamanhos e preços finais poderão ser definidos de acordo com a oferta real da marca.'], collection:['The collection','A coleção'], heading:['Sweet, simple,<br>considered.','Doce, simples,<br>pensado ao pormenor.'], intro:['A clear starting point for customers to browse before asking for a bespoke creation.','Um ponto de partida claro para os clientes consultarem antes de pedirem uma criação personalizada.'], items:[['Signature cakes','Bolos de assinatura','Layered cakes, soft finishes and thoughtful decoration.','Bolos em camadas, acabamentos suaves e uma decoração pensada ao pormenor.','Custom','Personalizado'],['Little treats','Pequenas tentações','Individual desserts and small boxes made for gifting.','Sobremesas individuais e pequenas caixas feitas para oferecer.','Boxes','Caixas'],['Celebration pieces','Peças para celebrações','A centrepiece for birthdays, milestones and special tables.','Um centro de mesa para aniversários, marcos importantes e mesas especiais.','Bespoke','Personalizado'],['Seasonal details','Detalhes sazonais','Limited collections shaped around the mood of the season.','Coleções limitadas inspiradas no ambiente de cada estação.','Limited','Limitado']], made:['Made for you','Feito para si'], specific:['Have something<br>specific in mind?','Tem algo<br>específico em mente?'], specificText:['Tell us the occasion, the feeling and the details that matter. We’ll use this conversation to shape the right cake for the moment.','Conte-nos a ocasião, o ambiente e os detalhes importantes. Usaremos esta conversa para criar o bolo certo para o momento.'], start:['Start an enquiry','Inicie um pedido'] },
  about: { title:['Our story — Fluffy Cakes','A nossa história — Fluffy Cakes'], description:['The Fluffy Cakes story demo','Demonstração da história da Fluffy Cakes'], eyebrow:['The feeling','A sensação'], hero:['More than<br><em>a cake.</em>','Mais do que<br><em>um bolo.</em>'], lead:['A demo story page for a brand built around care, beauty and the quiet joy of making something by hand.','Uma página de demonstração para uma marca construída em torno do cuidado, da beleza e da alegria tranquila de fazer algo à mão.'], story:['There is something special about a dessert made with intention. It slows the room down, gives people a reason to gather and turns an ordinary moment into a memory.','Há algo de especial numa sobremesa feita com intenção. Abranda o ritmo, dá às pessoas uma razão para se reunirem e transforma um momento comum numa memória.'], working:['Fluffy Cakes is a working demo concept. The final story, founder profile and production details can be added when Karen shares more about the brand.','Fluffy Cakes é um conceito de demonstração em desenvolvimento. A história final, o perfil da fundadora e os detalhes de produção poderão ser acrescentados quando Karen partilhar mais sobre a marca.'], lines:[['Made for the moment','Feito para o momento'],['Finished with care','Finalizado com cuidado'],['Shared with joy','Partilhado com alegria']], promise:['The promise','A promessa'], softness:['Softness with<br>a point of view.','Suavidade com<br>uma identidade própria.'], simple:['Simple design. Considered details. A warm experience from first visit to final bite.','Design simples. Detalhes pensados. Uma experiência acolhedora, da primeira visita à última garfada.'] },
  gallery: { title:['Gallery — Fluffy Cakes','Galeria — Fluffy Cakes'], description:['Fluffy Cakes gallery demo','Demonstração da galeria Fluffy Cakes'], eyebrow:['A visual taste','Uma prova visual'], hero:['Little moments,<br><em>beautifully made.</em>','Pequenos momentos,<br><em>feitos com beleza.</em>'], lead:['A gallery direction for showing finished cakes, details, celebrations and the Fluffy Cakes world.','Uma direção de galeria para mostrar bolos finalizados, detalhes, celebrações e o universo Fluffy Cakes.'], tiles:[['Signature finish','Acabamento de assinatura','A visual anchor for the future collection.','Uma referência visual para a futura coleção.'],['Celebrations','Celebrações','Birthdays, milestones and all the reasons to gather.','Aniversários, marcos importantes e todas as razões para reunir.'],['Sweet details','Detalhes doces','Texture, colour and small thoughtful touches.','Textura, cor e pequenos detalhes pensados.']], grows:['The gallery grows with the brand','A galeria cresce com a marca'], every:['Every cake<br>has a story.','Cada bolo<br>tem uma história.'], future:['This demo uses one supplied brand image. Future photography can be added here as the menu and portfolio develop.','Esta demonstração usa uma imagem de marca fornecida. Poderá acrescentar-se fotografia futura à medida que o menu e o portefólio evoluem.'] },
  contact: { title:['Contact & orders — Fluffy Cakes','Contacto e encomendas — Fluffy Cakes'], description:['Contact Fluffy Cakes demo','Demonstração de contacto da Fluffy Cakes'], eyebrow:['Let’s make something lovely','Vamos criar algo bonito'], hero:['Start with<br><em>an idea.</em>','Comece com<br><em>uma ideia.</em>'], lead:['A simple enquiry flow for custom cakes, celebration pieces and sweet details. This form is a demo and does not submit yet.','Um formulário simples para pedidos de bolos personalizados, peças para celebrações e detalhes doces. Este formulário é uma demonstração e ainda não envia pedidos.'], labels:['Name','Nome','Email','Email','Occasion','Ocasião','Date','Data','Tell us about your idea','Conte-nos a sua ideia'], placeholders:['Your name','O seu nome','you@example.com','voce@exemplo.pt','What are you celebrating?','O que está a celebrar?'], occasions:[['Birthday','Aniversário'],['Wedding','Casamento'],['Corporate','Corporativo'],['Just because','Só porque sim']], send:['Send enquiry','Enviar pedido'], note:['Demo interaction only — form not connected. Prefer a direct reply? Use the contact links alongside.','Apenas demonstração — o formulário não está ligado. Prefere uma resposta direta? Utilize os contactos ao lado.'], good:['Good to know','É bom saber'], thoughtful:['Thoughtful from the first message.','Cuidado desde a primeira mensagem.'], share:['Share the feeling you want to create. We’ll shape the details together.','Partilhe o ambiente que quer criar. Juntos, damos forma aos detalhes.'], call:['Call +351 929 106 710','Ligue +351 929 106 710'], submitNote:['Connect the real form when the contact details are confirmed.','Ligue o formulário real quando os dados de contacto estiverem confirmados.'] }
};

const page = document.body.dataset.page || 'home';
const lang = ['en','pt'].includes(localStorage.getItem(LANGUAGE_KEY)) ? localStorage.getItem(LANGUAGE_KEY) : 'en';
const t = key => (copy[page]?.[key] || copy.common[key] || [key,key])[lang === 'pt' ? 1 : 0];
const setText = (selector, value, index = 0, root = document) => {
  const el = root.querySelectorAll(selector)[index];
  if (el) el.innerHTML = value;
};
const setPair = (selector, pair, index = 0, root = document) =>
  setText(selector, typeof pair === 'string' ? pair : pair[lang === 'pt' ? 1 : 0], index, root);

function translatePage() {
  document.documentElement.lang = lang;
  document.title = t('title');
  const meta = document.querySelector('meta[name="description"]'); if (meta) meta.content = t('description');
  setPair('.skip', copy.common.skip); document.querySelector('.brand')?.setAttribute('aria-label', t('homeLabel')); document.querySelector('.brand-logo')?.setAttribute('alt', t('logoAlt')); setPair('.menu-toggle .sr-only', copy.common.openNav); setPair('.language-label', copy.common.languageLabel); document.querySelector('.language-switcher')?.setAttribute('aria-label', t('languageLabel'));
  const navKeys = ['home', 'menu', 'story', 'gallery'];
  document.querySelectorAll('#site-menu > a').forEach((el, i) => {
    if (navKeys[i]) el.textContent = t(navKeys[i]);
  });
  document.querySelectorAll('.floating-enquiry').forEach(el=>{el.textContent=t('enquire');el.setAttribute('aria-label',t('enquire'));});
  document.querySelectorAll('footer .footer-row span:first-child').forEach(el=>el.textContent=t('footer'));
  document.querySelectorAll('footer a').forEach((el,i)=>{if(i===0) el.textContent=t('email'); else el.textContent=t('whatsappLink');});
  document.querySelectorAll('.language-switcher button').forEach(button=>{const active=button.dataset.lang===lang;button.setAttribute('aria-pressed',String(active));button.classList.toggle('is-active',active);});
  if(page==='home') translateHome(); if(page==='menu') translateMenu(); if(page==='about') translateAbout(); if(page==='gallery') translateGallery(); if(page==='contact') translateContact();
}
function translateHome(){ [['.eyebrow','eyebrow'],['h1','hero'],['.hero .lead','lead'],['.actions .button', 'explore'],['.actions .button','conversation'],['.signature','signature'],['.art-note','art'],['.dark-section .kicker','feeling'],['.dark-section h2','more'],['.dark-section .section-intro','demoIntro'],['.story-copy p','story'],['.story-side p','side'],['#selection .kicker','taste'],['#selection h2','selection'],['#selection .section-intro','menuIntro'],['#contact .kicker','contactKicker'],['#contact h2','sweet'],['#contact p','contactIntro']].forEach(([s,k],i)=>setPair(s, t(k), s==='.actions .button'?i:0)); copy.home.lines.forEach((p,i)=>setPair('.line-list div',p,i)); copy.home.cards.forEach((p,i)=>{setPair('.menu-card h3',p,i);setPair('.menu-card p',p.slice(2,4),i);setPair('.menu-card .card-foot',p.slice(4,6),i);}); setPair('.quote blockquote',t('quote')); setPair('.quote cite', ['Fluffy Cakes · Karen Guilaze','Fluffy Cakes · Karen Guilaze']); const img=document.querySelector('.hero-photo');if(img)img.alt=t('artAlt');}
function translateMenu(){ [['.eyebrow','eyebrow'],['h1','hero'],['.page-hero .lead','lead'],['.section-head .kicker','collection'],['.section-head h2','heading'],['.section-head .section-intro','intro'],['.dark-section .kicker','made'],['.dark-section h2','specific'],['.dark-section .section-intro','specificText']].forEach(([s,k])=>setPair(s,t(k))); copy.menu.items.forEach((p,i)=>{setPair('.list-item h3',p,i);setPair('.list-item span',p.slice(2,4),i);setPair('.list-item em',p.slice(4,6),i);});setPair('.dark-section .button',t('start'));}
function translateAbout(){[['.eyebrow','eyebrow'],['h1','hero'],['.page-hero .lead','lead'],['.story-copy p','story'],['.story-side p','working'],['.soft-section .kicker','promise'],['.soft-section h2','softness'],['.soft-section .section-intro','simple']].forEach(([s,k])=>setPair(s,t(k)));copy.about.lines.forEach((p,i)=>setPair('.line-list div',p,i));}
function translateGallery(){[['.eyebrow','eyebrow'],['h1','hero'],['.page-hero .lead','lead'],['.section-head .kicker','grows'],['.section-head h2','every'],['.section-head .section-intro','future']].forEach(([s,k])=>setPair(s,t(k)));copy.gallery.tiles.forEach((p,i)=>{setPair('.gallery-tile h3',p,i);setPair('.gallery-tile p',p.slice(2,4),i);});}
function translateContact(){const c=copy.contact;[['.eyebrow','eyebrow'],['h1','hero'],['.page-hero .lead','lead'],['.contact-box .kicker','good'],['.contact-box h3','thoughtful'],['.contact-box p','share'],['.demo-note','note'],['form button','send']].forEach(([s,k])=>setPair(s,t(k)));const labels=document.querySelectorAll('form label');[['labels',0],['labels',2],['labels',4],['labels',6],['labels',8]].forEach(([_,i],n)=>{if(labels[n])labels[n].childNodes[0].textContent=c.labels[lang==='pt'?i+1:i]+' ';});const inputs=document.querySelectorAll('input,textarea');[0,2].forEach((i,n)=>{if(inputs[i])inputs[i].placeholder=c.placeholders[(lang==='pt'?1:0)+n*2];});if(document.querySelector('textarea'))document.querySelector('textarea').placeholder=c.placeholders[lang==='pt'?5:4];document.querySelectorAll('select option').forEach((el,i)=>el.textContent=c.occasions[i][lang==='pt'?1:0]);setPair('.contact-links a', ['fluffycakes.pt@gmail.com','fluffycakes.pt@gmail.com'],0);setPair('.contact-links a',c.call,1);setPair('.contact-links a',copy.common.whatsappLink,2);}

document.querySelectorAll('.language-switcher button').forEach(button=>button.addEventListener('click',()=>{localStorage.setItem(LANGUAGE_KEY,button.dataset.lang);location.reload();}));
if(page==='contact'){const form=document.querySelector('form');form?.addEventListener('submit',event=>{event.preventDefault();document.querySelector('.demo-note').textContent=t('submitNote');});}
translatePage();

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');observer.unobserve(entry.target)}}),{threshold:.14});
document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));
const progress=document.querySelector('.progress span');
const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(max>0?(scrollY/max)*100:0)+'%'};
addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();
document.querySelectorAll('.menu-toggle').forEach(button=>{button.addEventListener('click',()=>{const nav=button.closest('.nav');const open=nav.classList.toggle('nav-open');button.setAttribute('aria-expanded',String(open));button.querySelector('.sr-only').textContent=open?t('closeNav'):t('openNav');});button.closest('.nav').querySelectorAll('.nav-links a').forEach(link=>link.addEventListener('click',()=>{const nav=button.closest('.nav');nav.classList.remove('nav-open');button.setAttribute('aria-expanded','false');button.querySelector('.sr-only').textContent=t('openNav');}));});
addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.nav-open').forEach(nav=>{nav.classList.remove('nav-open');const button=nav.querySelector('.menu-toggle');if(button){button.setAttribute('aria-expanded','false');button.querySelector('.sr-only').textContent=t('openNav');}})});
